[package]
name = "llhf-global"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.3"
lazy_static = "1.4.0"
rdev = "0.5.3"